export default {
  base: {
    height: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
  },
  headlines: {
    // display: 'none',
    marginTop: '-100px',
    lineHeight: '2.6rem',
    textAlign: 'center',
    position: 'relative',
    top: '20px',
    width: '100%',
  },
  logoWrapper: {
    paddingTop: '100px',
    width: '100%',
  },
  circle: seen => ({
    height: 100,
    width: 100,
    borderRadius: '50%',
    background: '#7A1E48',
    margin: 'auto',
    display: 'block',
    opacity: seen ? '0' : '1',
    position: 'absolute',
    top: 0,
  }),
  flower: seen => ({
    transform: seen ? 'scale(1.2,)' : 'scale(0.6)',
  }),
  tagline: seen => ({
    opacity: seen ? '1' : '0',
    transform: seen ? 'translateY(30px)' : 'none',
    marginTop: '-100px',
  }),
  span: seen => ({
    display: 'inline-block',
    // float: 'left',
    transform: seen ? 'translateY(-85px)' : 'scaleY(0)',
    opacity: seen ? '1' : '0',
  }),
  logo: {
    height: 100,
    width: 100,
    fill: '#7A1E48',
    margin: '-150px auto auto',
    display: 'block',
    opacity: 1,
    position: 'relative',
    top: '-170px',
  },
  headline: {
    fontSize: '2.5rem',
  },
  socialLinks: seen => ({
    opacity: seen ? '1' : '0',
    transform: seen ? 'translateY(80px)' : 'none',
    position: 'relative',
    zIndex: '9',
  }),
  navLinks: seen => ({
    opacity: seen ? '1' : 0,
    marginTop: '2rem',
    transform: seen ? 'translateY(40px)' : 'none',
    width: '100%',
  }),
  socialLinksList: {
    textAlign: 'center',
    listStyleType: 'none',
  },
  homeContainer: {
    color: '#341931',
    position: 'relative',
    display: 'flex',
    paddingTop: 100,
    flexDirection: 'column',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.5s',
    width: '100%',
  },
};
