export default {
  base: {
    height: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headlines: {
    display: 'none',
    lineHeight: '2.6rem',
    textAlign: 'center',
    width: '100%',
  },
  logoWrapper: {
    paddingTop: '100px',
    width: '100%',
  },
  circle: {
    height: 100,
    width: 100,
    borderRadius: '50%',
    background: '#7A1E48',
    margin: 'auto',
    display: 'block',
    opacity: '1',
    position: 'absolute',
    top: 0,
  },
  logo: {
    height: 100,
    width: 100,
    fill: '#7A1E48',
    margin: 'auto',
    display: 'block',
    opacity: 1,
    position: 'relative',
    top: '-250px',
  },
};
