export default {
  base: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: '100vh',
    padding: '8rem 4rem 4rem',
    width: '100%',
    '@media screen and (max-width: 64em)': {
      marginBottom: '2rem',
      padding: '6rem 1rem 1rem',
    },
  },
  button: hover => ({
    background: '#FFF',
    border: hover ? '1px solid rgba(157, 32, 83,0.7)' : 'none',
    boxShadow: hover ? 'inset 0 0 10px rgb(157, 32, 83, .2), 0 0 10px rgba(157, 32, 83, .1)' : 'inset 0 0 20px rgba(157, 32, 83, 0)',
    cursor: 'pointer',
    display: 'block',
    fontSize: '1.2rem',
    height: 45,
    lineHeight: hover ? '44px' : '45px',
    margin: '40px auto 0',
    maxWidth: '90%',
    outline: '0',
    outlineColor: hover ? 'rgba(157, 32, 83, 0)' : 'rgba(0, 0, 0, .2)',
    outlineOffset: hover ? 15 : 0,
    outlineStyle: 'solid',
    outlineWidth: 1,
    position: 'relative',
    textAlign: 'center',
    textDecoration: 'none',
    textTransform: 'uppercase',
    transition: 'all 1000ms cubic-bezier(0.19, 1, 0.22, 1)',
    verticalAlign: 'middle',
    width: '100%',
    zIndex: 999,
  }),
  headline: {
    fontSize: '1.8rem',
    lineHeight: '2.3rem',
    marginBottom: '1rem',
    textAlign: 'center',
    width: '46rem',
    '@media screen and (max-width: 46.5em)': {
      maxWidth: '90%',
    },
  },
  tagline: {
    fontSize: '1.4rem',
    lineHeight: '1.8rem',
    marginBottom: '2rem',
    textAlign: 'center',
    '@media screen and (max-width: 64em)': {
      marginBottom: '1rem',
    },
  },
  projectTitle: {
    display: 'flex',
    fontSize: '1.4rem',
    width: '100%',
    '@media screen and (max-width: 64em)': {
      textAlign: 'center',
    },
  },
  projectWrapper: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: '5vh',
    padding: '2rem',
    width: '100%',
    '@media screen and (max-width: 64em)': {
      flexDirection: 'column',
      marginBottom: '0',
      padding: 0,
    },
  },
  projectLogo: {
    display: 'block',
    margin: '0 auto 1.6rem',
    maxWidth: '65%',
    '@media screen and (max-width: 64em)': {
      width: '100%',
      maxWidth: 200,
    },
  },
  projectImage: {
    borderRadius: '3px',
    boxShadow: '0 10px 20px rgba(0, 0, 0, 0.1), 0 6px 6px rgba(0, 0, 0, 0.15)',
    height: 'auto',
    maxWidth: '100%',
    transition: 'all 0.2s',
    ':hover': {
      boxShadow: '0 14px 24px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.15)',
    },
  },
  projectImageWrapper: order => ({
    order: order === 'odd' ? '1' : '2',
    padding: '2rem',
    width: '66%',
    '@media screen and (max-width: 64em)': {
      order: '2',
      width: '100%',
    },
  }),
  projectDescriptionWrapper: order => ({
    fontSize: '1.4rem',
    lineHeight: '2rem',
    order: order === 'odd' ? '2' : '1',
    padding: '0.8rem',
    textAlign: 'center',
    width: '33%',
    '@media screen and (max-width: 64em)': {
      marginTop: '2rem',
      order: '1',
      width: '100%',
    },
  }),
  footerType: {
    fontSize: '1.2rem',
    lineHeight: '1.8rem',
    marginTop: '1rem',
    textAlign: 'center',
  },
};
