export default {
  base: {
    alignItems: 'center',
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    padding: '8rem 4rem 4rem',
    flexDirection: 'column',
    justifyContent: 'center',
    '@media screen and (max-width: 64em)': {
      padding: '6rem 1rem 1rem',
      marginBottom: '2rem',
    },
  },
  headline: {
    fontSize: '1.8rem',
    lineHeight: '2.3rem',
    marginBottom: '1rem',
    textAlign: 'center',
    width: '46rem',
    '@media screen and (max-width: 46.5em)': {
      maxWidth: '90%',
    },
  },
  tagline: {
    fontSize: '1.4rem',
    lineHeight: '2rem',
    marginBottom: '2rem',
    textAlign: 'center',
    width: '100%',
    maxWidth: '40rem',
    '@media screen and (max-width: 64em)': {
      marginBottom: '1rem',
    },
  },
  socialLinks: seen => ({
    marginTop: '3rem',
    opacity: seen ? '1' : '0',
    transform: seen ? 'translateY(20px)' : 'none',
  }),
  navLinks: seen => ({
    opacity: seen ? '1' : 0,
    transform: seen ? 'translateY(20px)' : 'none',
  }),
  socialLinksList: {
    textAlign: 'center',
    listStyleType: 'none',
  },
  input: {
    border: 0,
    outline: 0,
    marginBottom: '0.65rem',
    borderRadius: 3,
    fontSize: '1.2rem',
    padding: '0.5rem 0.5rem 0.5rem 0.65rem',
    width: '100%',
    background: '#EFEFEF',
  },
  submit: hover => ({
    background: '#FFF',
    border: hover ? '1px solid rgba(157, 32, 83,0.7)' : 'none',
    boxShadow: hover ? 'inset 0 0 10px rgb(157, 32, 83, .2), 0 0 10px rgba(157, 32, 83, .1)' : 'inset 0 0 20px rgba(157, 32, 83, 0)',
    cursor: 'pointer',
    display: 'block',
    fontSize: hover ? '1.22rem' : '1.2rem',
    height: 45,
    lineHeight: hover ? '44px' : '45px',
    maxWidth: 160,
    outline: '0',
    outlineColor: hover ? 'rgba(157, 32, 83, 0)' : 'rgba(0, 0, 0, .2)',
    outlineOffset: hover ? 15 : 0,
    outlineStyle: 'solid',
    outlineWidth: 1,
    position: 'relative',
    textAlign: 'center',
    textDecoration: 'none',
    textTransform: 'uppercase',
    transition: 'all 1000ms cubic-bezier(0.19, 1, 0.22, 1)',
    verticalAlign: 'middle',
    width: '100%',
    '@media screen and (max-width: 64em)': {
      marginBottom: 8,
    },
  }),
};
