export default {
  base: hover => ({
    background: '#FFF',
    border: hover ? '1px solid rgba(353, 74, 91,0.7)' : 'none',
    boxShadow: hover ? 'inset 0 0 10px rgb(353, 74, 91, .2), 0 0 10px rgba(353, 74, 91, .1)' : 'inset 0 0 20px rgba(353, 74, 91, 0)',
    cursor: 'pointer',
    display: 'block',
    fontSize: '1.2rem',
    height: 45,
    lineHeight: hover ? '44px' : '45px',
    outline: '0',
    outlineColor: hover ? 'rgba(353, 74, 91, 0)' : 'rgba(0, 0, 0, .2)',
    outlineOffset: hover ? 15 : 0,
    outlineStyle: 'solid',
    outlineWidth: 1,
    position: 'relative',
    textAlign: 'center',
    textDecoration: 'none',
    textTransform: 'uppercase',
    transition: 'all 1000ms cubic-bezier(0.19, 1, 0.22, 1)',
    verticalAlign: 'middle',
    width: '100%',
  }),
  buttonWrapper: isHeader => ({
    alignItems: 'center',
    display: 'flex',
    margin: '0 auto 10px',
    width: '30%',
    '@media screen and (max-width: 64em)': {
      alignItems: 'center',
      display: isHeader ? 'none' : 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      width: '100%',
    },
  }),
};
