export default {
  base: hover => ({
    border: hover ? '1px solid rgba(0,0,0,0.2)' : 'none',
    boxShadow: hover ? 'inset 0 0 10px rgba(0, 0, 0, .2), 0 0 10px rgba(0, 0, 0, .1)' : 'inset 0 0 20px rgba(0, 0, 0, 0)',
    cursor: 'pointer',
    display: 'block',
    height: 45,
    lineHeight: '45px',
    maxWidth: 160,
    outline: '0',
    outlineColor: hover ? 'rgba(0, 0, 0, 0)' : 'rgba(0, 0, 0, .2)',
    outlineOffset: hover ? 15 : 0,
    outlineStyle: 'solid',
    outlineWidth: 1,
    position: 'relative',
    textAlign: 'center',
    textDecoration: 'none',
    textTransform: 'uppercase',
    transition: 'all 1000ms cubic-bezier(0.19, 1, 0.22, 1)',
    verticalAlign: 'middle',
    width: '100%',
  }),
  buttonWrapper: {
    width: '30%',
  },
};
